@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion
cd /d "%~dp0"

set "OUT_FILE=%~dp0pat.js"

echo ============================================================
echo   9178GG - Write GitHub PAT to local file (pat.js)
echo   After saving, admin.html will read PAT automatically.
echo ============================================================
echo.
echo Paste your GitHub Personal Access Token below.
echo  (Starts with "ghp_" for classic token, or arbitrary length
echo   for fine-grained token.  Right-click title bar -> Paste,
echo   or Ctrl+V in Windows Terminal / cmd.exe)
echo.
echo To cancel: leave it empty and press Enter.
echo.

set "PAT_INPUT="
set /p "PAT_INPUT=> PAT: " || goto :err_prompt

if "%PAT_INPUT%"=="" (
  echo.
  echo [Cancel] Nothing written (you pasted nothing).
  echo.
  pause
  exit /b 0
)

REM ---- Write pat.js ------------------------------------------------------
echo.
echo Writing PAT to:
echo   %OUT_FILE%
echo.

(
echo /**
echo  * Auto-generated by "1-写入PAT到本地.bat".
echo  * NEVER commit this file to GitHub - it's IGNORED via .gitignore.
echo  * Only stored on YOUR computer.
echo  */
echo window._GH_PAT = '!PAT_INPUT!';
) > "%OUT_FILE%" 2>nul

if errorlevel 1 goto :err_write

REM ---- Verify written content -------------------------------------------
echo Verifying...
findstr /C:"window._GH_PAT" "%OUT_FILE%" >nul 2>&1
if errorlevel 1 goto :err_write

echo.
echo ============================================================
echo  Done! PAT saved to pat.js
echo.
echo  Next steps:
echo    1. Open admin.html (or double-click 9178后台管理 shortcut)
echo    2. You'll see "已从本地 pat.js 自动读取 PAT" on login page
echo    3. Enter password and click Login - PAT is already filled.
echo.
echo  To change PAT later: just re-run this .bat again.
echo ============================================================
echo.
pause
exit /b 0

:err_prompt
echo.
echo [ERROR] Failed to read your input. Try running this bat again.
pause
exit /b 1

:err_write
echo.
echo [ERROR] Cannot write to "%OUT_FILE%"
echo Possible reasons:
echo   - File is read-only or locked by another program
echo   - No write permission to folder J:\9178GG
echo Please close any open admin.html that may be using pat.js and try again.
echo.
pause
exit /b 2
