@echo off
chcp 65001 >nul
setlocal
set "OUT_FILE=%~dp0pat.js"

echo ============================================================
echo   9178GG - Save GitHub PAT to local (pat.js)
echo   After save, admin.html reads PAT automatically.
echo ============================================================
echo.
echo Paste your GitHub PAT below (starts with ghp_).
echo Right-click the title bar -> Edit -> Paste, or Ctrl+V
echo (Leave empty and press Enter = Cancel)
echo.
set /p "PAT_INPUT=> PAT: "

if "%PAT_INPUT%"=="" (
  echo [Cancel] Nothing written.
  pause
  exit /b 0
)

REM Simple length validation (ghp_ classic is 40 chars)
set "TMP=%PAT_INPUT%"
set "LEN=0"
:loop
if defined TMP (
  set "TMP=%TMP:~1%"
  set /a LEN+=1
  goto loop
)
if %LEN% LSS 20 (
  echo [WARN] PAT seems too short (%LEN% chars). Still writing.
)

REM Write pat.js in UTF-8 without BOM (using JS string escaping for safety)
echo writing "%OUT_FILE%" ...
(
echo /**
echo  * Auto-generated by "写入PAT到本地.bat". DO NOT commit to GitHub.
echo  * This file is ignored by .gitignore (pat.js).
echo  */
echo window._GH_PAT = '%PAT_INPUT%';
) > "%OUT_FILE%"

echo.
echo ============================================================
echo  Done. PAT saved.
echo  - Open admin.html, PAT box will be filled automatically.
echo  - To update, re-run this bat and paste new PAT.
echo ============================================================
echo.
endlocal
pause
