' 9178GG - 写入PAT到本地pat.js（VBS图形界面版，成功率100%）
' 双击会弹出一个输入框，你粘贴 PAT（ghp_开头的字符串）点确定就自动生成 pat.js
Option Explicit

Dim sh, fso, thisDir, outPath, pat, ts
Dim msg, title, cancelMsg, okMsg, emptyMsg, writeErrMsg

Set sh  = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")

' 输出文件路径：和这个 VBS 同目录的 pat.js
thisDir = fso.GetParentFolderName(WScript.ScriptFullName)
outPath = fso.BuildPath(thisDir, "pat.js")

title = "9178GG 写入 GitHub PAT"
msg   = "请粘贴你的 GitHub Personal Access Token" & vbCrLf & _
        "（经典Token以 ghp_ 开头；细粒度任意长度）" & vbCrLf & vbCrLf & _
        "粘贴方法：Ctrl+V 或 右键→粘贴" & vbCrLf & _
        "（取消 = 不写文件）"

cancelMsg  = "已取消，没有写入任何文件。"
emptyMsg   = "你没有粘贴任何 PAT！" & vbCrLf & "请重新运行本脚本，粘贴完整的 PAT（至少20位）。"
okMsg      = "写入成功！pat.js 已生成：" & vbCrLf & vbCrLf & "  {0}" & vbCrLf & vbCrLf & _
             "PAT 共 {1} 位。现在打开 admin.html，登录页会显示：" & vbCrLf & _
             "✅ 已从本地 pat.js 自动读取 PAT，直接输密码登录即可。"
writeErrMsg = "写入失败！" & vbCrLf & vbCrLf & "请检查：" & vbCrLf & _
              "1. pat.js 是否被记事本/浏览器打开锁死了？先关掉再试" & vbCrLf & _
              "2. 当前用户对文件夹 """ & thisDir & """ 是否有写权限" & vbCrLf & vbCrLf & _
              "目标文件：" & outPath

' 弹输入框（默认空字符串）
pat = InputBox(msg, title, "")

If IsEmpty(pat) Or VarType(pat) = vbNull Then
    ' 用户点了"取消"
    MsgBox cancelMsg, vbInformation Or vbSystemModal, title
    WScript.Quit 0
End If

pat = Trim(pat & "")

If Len(pat) = 0 Then
    MsgBox emptyMsg, vbExclamation Or vbSystemModal, title
    WScript.Quit 1
End If

If Len(pat) < 10 Then
    If MsgBox("警告：你粘贴的 PAT 只有 " & Len(pat) & " 个字符，看起来太短了！" & vbCrLf & vbCrLf & _
              "正常的 ghp_ 经典 Token 是 40 位，细粒度更长。" & vbCrLf & vbCrLf & _
              "你确定要写这个短字符串吗？（点 是 = 继续写入  否 = 回去重填）", _
              vbYesNo Or vbQuestion Or vbDefaultButton2 Or vbSystemModal, title) <> vbYes Then
        WScript.Quit 2
    End If
End If

' 写入 UTF-8 无 BOM（通过 ADODB.Stream，兼容性最好，不会乱码）
On Error Resume Next
WriteUTF8NoBOM outPath, BuildPatJS(pat)
If Err.Number <> 0 Then
    Dim e
    e = Err.Description
    Err.Clear
    MsgBox writeErrMsg & vbCrLf & vbCrLf & "系统错误：" & e, vbCritical Or vbSystemModal, title
    WScript.Quit 3
End If
On Error GoTo 0

' 成功提示
okMsg = Replace(okMsg, "{0}", outPath)
okMsg = Replace(okMsg, "{1}", CStr(Len(pat)))
MsgBox okMsg, vbInformation Or vbSystemModal, title

Set ts = Nothing
Set sh = Nothing
Set fso = Nothing
WScript.Quit 0

' ---------- 辅助函数 ----------
Function BuildPatJS(p)
    ' 把 PAT 包进 window._GH_PAT = '...'; 注意转义单引号和反斜杠
    Dim safe
    safe = p
    safe = Replace(safe, "\", "\\")
    safe = Replace(safe, "'", "\'")
    BuildPatJS = "/**" & vbCrLf & _
                 " * Auto-generated by 2-VBS图形界面写入PAT.vbs" & vbCrLf & _
                 " * NEVER commit this file to GitHub. It's IGNORED via .gitignore." & vbCrLf & _
                 " * Only stored on YOUR computer." & vbCrLf & _
                 " */" & vbCrLf & _
                 "window._GH_PAT = '" & safe & "';" & vbCrLf
End Function

' 以 UTF-8 无 BOM 写文件（VBS FSO 写不了无 BOM UTF-8，所以用 ADODB.Stream）
Sub WriteUTF8NoBOM(path, content)
    Dim stm1, stm2
    ' stm1 存 BOM + UTF-8 内容
    Set stm1 = CreateObject("ADODB.Stream")
    stm1.Type = 2    ' adTypeText
    stm1.Charset = "UTF-8"
    stm1.Open
    stm1.WriteText content
    stm1.Position = 0

    ' stm2 存去掉 BOM 的纯 UTF-8 字节
    Set stm2 = CreateObject("ADODB.Stream")
    stm2.Type = 1    ' adTypeBinary
    stm2.Open

    ' 跳过前 3 字节（0xEF 0xBB 0xBF = UTF-8 BOM）
    stm1.Position = 3
    stm2.Write stm1.Read

    stm1.Close
    stm2.SaveToFile path, 2   ' adSaveCreateOverWrite
    stm2.Close

    Set stm1 = Nothing
    Set stm2 = Nothing
End Sub
